import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/src/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // testing variables
  const nodeEnv = process.env.NODE_ENV;
  const clientVar = process.env.NEXT_PUBLIC_CLIENTVAR;

  return (
    <>
      <Head>
        <title>Testy McTestFace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Testy McTestFace
          </h1>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div className="text-white text-lg">
          <p>Testing Variables, client and server:</p>
          <p>
            Node ENV: {nodeEnv}
          </p>
          <p>
            Client Var: {clientVar}
          </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
